name: Build Application

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          # Windows x64
          - os: windows-latest
            arch: x64
            platform: win
          # macOS Intel (x64)
          - os: macos-latest
            arch: x64
            platform: mac
            build-script: mac:intel

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Windows (NSIS)
        if: matrix.platform == 'win'
        run: npm run win -- --arch=${{ matrix.arch }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CSC_IDENTITY_AUTO_DISCOVERY: false

      - name: Build macOS (DMG + ZIP)
        if: matrix.platform == 'mac'
        run: npm run ${{ matrix.build-script }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CSC_IDENTITY_AUTO_DISCOVERY: false

      - name: Upload build artifacts (Windows)
        if: matrix.platform == 'win'
        uses: actions/upload-artifact@v4
        with:
          name: NeoEarth-Windows-${{ matrix.arch }}
          path: dist/*.exe

      - name: Upload build artifacts (macOS)
        if: matrix.platform == 'mac'
        uses: actions/upload-artifact@v4
        with:
          name: NeoEarth-Mac-${{ matrix.arch }}
          path: |
            dist/*.dmg
            dist/*.zip