name: Build NeoEarth

on:
  push:
    tags: [ 'v*.*.*' ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        arch: [x64]
        # macOS does not support arm64 architecture directly
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build Windows (x64)
        if: runner.os == 'Windows'
        run: npm run build:win
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build macOS (x64)
        if: runner.os == 'macOS'
        run: npm run build:mac-x64
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifacts for Windows
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: NeoEarth-Windows-x64
          path: dist/*.exe

      - name: Upload artifacts for macOS
        if: runner.os == 'macOS'
        uses: actions/upload-artifact@v4
        with:
          name: NeoEarth-Mac-x64
          path: |
            dist/*.dmg
            dist/*.zip