name: Build NeoEarth

on:
  push:
    tags: [ 'v*.*.*' ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        arch: [x64, arm64]
        exclude:
          - os: windows-latest
            arch: arm64 
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Configuration Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Installation des dépendances
        run: npm install

      - name: Build Windows (x64/arm64)
        if: runner.os == 'Windows'
        run: npm run build:win -- --arch ${{ matrix.arch }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build macOS (x64/arm64)
        if: runner.os == 'macOS'
        run: npm run build:mac -- --arch ${{ matrix.arch }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artefacts Windows
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: NeoEarth-Windows-${{ matrix.arch }}
          path: dist/*.exe

      - name: Upload artefacts macOS
        if: runner.os == 'macOS'
        uses: actions/upload-artifact@v4
        with:
          name: NeoEarth-Mac-${{ matrix.arch }}
          path: |
            dist/*.dmg
            dist/*.zip
